### PR TITLE
embed tweet

### PR DESCRIPTION
**Pull request by ykris45**
embedding tweet widgets

### CODE REVIEW

**Comment by tzarebczan** [comment]
@ykris45 can you put this at the end instead?

**Comment by ykris45** [comment]
yes i can. please wait at least 10 minutes from now

**Comment by tzarebczan** [comment]
Thanks @ykris45 !

**Comment by tzarebczan** [comment]
@ykris45 think I'm going to remove this since it just repeats what's already said in the blog and the same GIF.

**Pull request merged**
