### PR TITLE
FIX #386 added contact us and redirect to hello@lbry.io ( TESTED Locally)

### LINKED ISSUE #386: Add 'Contact Us' page / link or link to email contact
Currently, when navigating through the main lbry.io pages, there's no easy access to contact information. 

We should:
a) create a contact us page and link to it from main header/footers Page would also have office info/contact phone number? 
or 
b) add email contact button which goes to hello@lbry.io to main header/footers

### PR DESCRIPTION
**Pull request by ykris45**

### CODE REVIEW

**Comment by ykris45** [comment]
image

**Comment by tzarebczan** [comment]
@ykris45 please add the Contact Us text to https://github.com/lbryio/lbry.io/blob/6f28ae433c0d88461ffd6276dbdb602090f59f68/data/i18n/en.yaml#L87 and reference that on the learn page similar to how Join Us is: {{learn.join}}

This ensures we cover our bases for internationalization later on.

**Comment by ykris45** [comment]
@tzarebczan 
image done..

**Comment by tzarebczan** [comment]
Thanks @ykris45 !!

**Pull request merged**
