### PR TITLE
 Add Yt sync page

### PR DESCRIPTION
**Pull request by ykris45**
image

my suggestion to gain more youtubers sync with LBRY Protocol

### CODE REVIEW

**Comment by tzarebczan** [comment]
@robvsmith / @kauffj what do you think about this addition?

**Comment by kauffj** [comment]
@tzarebczan it ought to be added to this page but not precisely in this fashion. I'll review and fix.

**Comment by ykris45** [comment]
image
i had other ideas but ya just share my idea...hehe

**Comment by kauffj** [comment]
Addressed in https://github.com/lbryio/lbry.io/commit/2697cd65b95c3ebf01ad279f11c0bb9bec777c38 but I still dislike this. Opening separate private ticket related to this.

**Pull request closed without merging**
