### PR TITLE
underline download lbry

### PR DESCRIPTION
**Pull request by ykris45**

### CODE REVIEW

**Comment by ykris45** [comment]
image

**Comment by kauffj** [comment]
@ykris45 add css class `link-primary` to the `<a>` tag

**Comment by ykris45** [comment]
@kauffj where i can add this class? sir

**Comment by ykris45** [comment]
@kauffj im finished sir

**Comment by ykris45** [comment]
tested on my android machine 
screenshot_2018-03-15-04-11-21-306

**Comment by kauffj** [comment]
@ykris45 now remove the `<u>` tag

**Comment by ykris45** [comment]
@kauffj done sir

**Comment by kauffj** [comment]
@ykris45 we're going to turn you into a programmer yet

**Comment by ykris45** [comment]
@kauffj . thanks sir.. i will learning and laerning to be as programmer... Gbu

**Pull request merged**
