### PR TITLE
Grammar correction of the FAQ

### PR DESCRIPTION
**Pull request by Grindelek**
Fixed grammar mistakes. (I hope this was the required format.)

### CODE REVIEW

**Comment by Grindelek** [comment]
@tzarebczan I think that I'm not authorised to solve the conflicts. Am I right?

**Comment by tzarebczan** [comment]
@Grindelek that's correct, we'll need to do it on our end. This happens when changes were made on master since the time you originally pulled the data.

Thanks again for doing this, we'll review. Please see https://lbry.io/faq/tips

**Comment by Grindelek** [comment]
@tzarebczan Alright. Should I wait to claim my bounty until it'll be merged? 
By the way, I've started to review the news, too.

**Comment by tzarebczan** [comment]
@Grindelek you can ahead and send the email with the link to this PR, we'll get it added to the queue.

**Pull request merged**
