### PR TITLE
add widget

### PR DESCRIPTION
**Pull request by ykris45**

### CODE REVIEW

**Comment by tzarebczan** [comment]
@ykris45 please remove the referrer id and add a screenshot of what it looks like. Thanks

**Comment by ykris45** [comment]
@tzarebczan done

**Comment by tzarebczan** [comment]
I meant add a screenshot to this PR of what it looks like running locally :) The github preview doesn't seem to show it when I tried. You can remove that other screenshot from the post.

**Comment by ykris45** [comment]
@tzarebczan 
image
it should like my past pull request was merged by julie on may updates sir. the widget automatically centered

**Comment by tzarebczan** [comment]
Thanks @ykris45 !

**Pull request merged**
