### PR TITLE
Update stephan-kinsella.md

### PR DESCRIPTION
**Pull request by SimonKev**
Stephan Kinsella "Lousiana State University" -> "Louisiana S.U."

### CODE REVIEW

**Comment by lyoshenka** [comment]
@SimonKev i appreciate all the spelling/grammar/typo fixes, but it would be far simpler to review and merge them all if you created a single PR with all your work, instead of opening 30+ separate PRs. Could you please combine all your changes into one PR, or at least do that from now on. Thanks.

**Comment by SimonKev** [comment]
Yes, I know. We tried to find a solution for it together with the devs on the #dev LBRY slack, but we couldn't find one. If you can guide me trough it, I'd be more than happy to merge them, I just don't know how.

 

Sent: Thursday, July 13, 2017 at 8:57 PM

**Comment by lyoshenka** [comment]
Looks like you have a fork of the repo [here](https://github.com/SimonKev/lbry.io/branches/active), and each of your PRs is a separate branch. If you check out master in your repo, then `cherry-pick -n` all the branches, you'll get a combined set of changes. Commit that in a new branch, then create a PR from that branch. 

You can probably even automate it with something like this (warning, I didn't test this, just typed it into github):

```
git checkout master
for i in seq 1 43; do git cherry-pick -n patch-$i; done
```

**Comment by SimonKev** [comment]
I don't know how to do that, could you please guide me on slack, step by step?

 
 

Sent: Thursday, July 13, 2017 at 9:16 PM

**Comment by kauffj** [comment]
@lyoshenka I don't really mind these being individual PRs, I'm just going to merge them

**Pull request merged**
