### PR TITLE
alternative to fix mobile issue

### PR DESCRIPTION
**Pull request by ykris45**
set height it will looks like tis screenshot
image

### CODE REVIEW

**Comment by ykris45** [comment]
screenshot_2018-08-16-03-28-38-989
Mobile View @tzarebczan

**Comment by ykris45** [comment]
Desktop Preview
image. if use mobile version its using height on the css and if using desktop version its using width on the css class. arternative method

**Comment by tzarebczan** [comment]
This is an attempt to fix https://github.com/lbryio/lbry.io/issues/531 

I'll let @NetOperatorWibby take a look, maybe he has other ideas.

**Comment by ykris45** [comment]
yessir.. 
image
For Now the Css class for this button is only applied to the _learnfooter.php and it can't broke any css element on the lbry.io site @tzarebczan ..

**Comment by ykris45** [comment]
@NetOperatorWibby Thanks Mr Paul.. Gbu

**Pull request merged**
