### PR TITLE
Create acceptable-use-policy.md

### PR DESCRIPTION
**Pull request by jsigwart**
Initial commit. #391

### CODE REVIEW

**Comment by tzarebczan** [comment]
Is this intended to be a publisher FAQ?

**Comment by kauffj** [comment]
@tzarebczan this is a slow-moving reaction to lbrywallet.com and potentially similar situations.

**Comment by jsigwart** [comment]
It was suggested this be done as a FAQ, and I added it as a Publisher FAQ. Thanks for catching that, Tom, because you're right, it is more broad than just publishing. Should we make a different category for AUP, Privacy Policy, and ToS? Trying to think of a good category name... suggestions?

**Comment by tzarebczan** [comment]
@jsigwart we should put it in the Other category - I don't think we want to make a new category unless we have a few related items to go into it. If you don't agree, let's discuss.

**Comment by jsigwart** [comment]
That makes complete sense. When we have more articles for a new category,
then we can create it and move this article.

**Comment by tzarebczan** [comment]
@jsigwart should we merge this or it needs additional eyes?

**Comment by jsigwart** [comment]
This is set to go now.

**Pull request merged**
