### PR TITLE
Update support.md

### PR DESCRIPTION
**Pull request by Grindelek**
Grammar correction.

### CODE REVIEW

**Comment by tzarebczan** [comment]
@Grindelek for future PRs, can you please group multiple changes into a single PR. If you make a change on one branch, continue adding to that branch and then PR it.

**Comment by Grindelek** [comment]
Of course, I'll try it, but I'm new at GitHub, so could you give some hint about it or link a tutorial?

**Comment by tzarebczan** [comment]
@Grindelek check out: https://github.com/WGBH/pbucore/wiki/Contributing-to-the-project-through-Github-web-interface

**Comment by tzarebczan** [comment]
@Grindelek I haven't reviewed all of these yet, but it looks like you were on a different branch when making changes. This PR is also trying to merge those changes into lbryio:feb-update as opposed to master. Going to close - please resubmit after reading through the github docs.

**Pull request closed without merging**
