### PR TITLE
add lbry shop on footer

### PR DESCRIPTION
**Pull request by ykris45**
based on this issues #561

### CODE REVIEW

**Comment by tzarebczan** [comment]
@ykris45 can you add a screenshot of how this looks?

**Comment by ykris45** [comment]
screenshot_2018-05-17-21-26-15-202
@

**Comment by tzarebczan** [comment]
@ykris45 that's definitely not what we want :) 

@kauffj  / @maximest-pierre any thoughts on where/how this should live in the footer?

**Comment by kauffj** [comment]
I'm not sure it should :)

Though /learn seems in appropriate as well.

I suppose I don't object to it being after "News" in the footer and before the icons.

**Comment by tzarebczan** [comment]
@ykris45 closing this for now, see comments above if you want to give this another shot. Sounds like adding it to the learn page and footer after news. Maybe you can find an icon to go with it.

**Pull request closed without merging**
