### PR TITLE
Update composer to version 1.6.5 from 1.5.2

### PR DESCRIPTION
**Pull request by maximest-pierre**
Update composer binary to the latest version

### CODE REVIEW

**Comment by tzarebczan** [comment]
@maximest-pierre was this tested locally? Does it need to be reviewed?

**Comment by ykris45** [comment]
@tzarebczan this is just update binary for composer to the newest version. and same with jquery before.

**Comment by maximest-pierre** [comment]
It was tested locally. To test it you only need to clone the repo in a temp directory and run the ```dev.sh```.

**Comment by tzarebczan** [comment]
LGTM, pushing.

**Pull request merged**
