### PR TITLE
Wrapped onclick function in video player to fix safari bug

### PR DESCRIPTION
**Pull request by kushalj**
wrapped onclick in video player with anonymous function to fix safari-wont-pause bug

### CODE REVIEW

**Comment by tzarebczan** [comment]
@kushalj Thanks for submitting this PR! Have you tested this on Non-Safari browsers to see if it breaks anything? 

Will give it a whirl later today and have @NetOperatorWibby take a look at the code changes.

**Comment by tzarebczan** [comment]
Oh yea, @kushalj please see https://lbry.io/faq/tips if you'd like to be tipped in LBC for your work :)

**Comment by NetOperatorWibby** [comment]
This looks good to me.

**Comment by kauffj** [comment]
This is a DRY violation but the original one was too, so I suppose it's fine.

@NetOperatorWibby now that you own this repo if you approve something you can/should just merge it. If you want another set of eyes on it, then explicitly assign me (and mention me if I don't do it within 24-48 hours), but otherwise you can merge on your own.

**Comment by kushalj** [comment]
Hi,

 I tested chrome and it was fine. thanks

**Pull request merged**
