### PR TITLE
Update composer to version 1.7.2 from 1.6.5

### PR DESCRIPTION
**Pull request by ykris45**
https://getcomposer.org/download/ i download composer binary via this link. and upload in my branch and clone it on temp folder and ran dev.sh on my local test,

### CODE REVIEW

**Comment by NetOperatorWibby** [comment]
What do the contents of this file look like?

**Comment by ykris45** [comment]
@NetOperatorWibby just run dev.sh and you will know sir

**Comment by ykris45** [comment]
i download via getcomposer.org and deploy in to my PR

**Comment by ykris45** [comment]
i referenced this PR#574

**Pull request merged**
