### PR TITLE
youtube.scss

### PR DESCRIPTION
**Pull request by ykris45**
converting yt.css to youtube.scss using tools converter

### CODE REVIEW

**Comment by ykris45** [comment]
#425 i using chrome css to scss converter

**Comment by ykris45** [comment]
@tzarebczan i think it almost done sir.

**Comment by maximest-pierre** [comment]
@ykris45 your branch is not up to date with the new youtube page change on the master branch.

**Comment by kauffj** [comment]
@maximest-pierre I think you're going to have to do this one, see comments made in slack a few minutes ago.

**Pull request closed without merging**
