### PR TITLE
Update incompatible-protocol-version.md

### PR DESCRIPTION
**Pull request by ykris45**
add screenshot

### CODE REVIEW

**Comment by ykris45** [comment]
@tzarebczan here you are

**Comment by tzarebczan** [comment]
@ykris45 can you make it smaller (and wider), just to include the box with the warning (so that it doesn't take up a lot of real estate on the page?  Please add a screenshot too

**Comment by ykris45** [comment]
@tzarebczan okay i'll today sir.

**Comment by ykris45** [comment]
done

**Pull request merged**
