### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by ykris45**
because the repository needs composer

### CODE REVIEW

**Comment by tzarebczan** [comment]
@maximest-pierre can you confirm composer needs to be installed? I haven't tried stepping through since the last time it was failing.

**Comment by maximest-pierre** [comment]
No composer does not need to be install on the system. If you look the .phar package is already at the root and all the script are using that one and not the local version. I tested it a week ago when we discovered that the ./dev.sh script was acting weird.

**Comment by tzarebczan** [comment]
@ykris45 can you try this on a clean VM for Windows/Linux somewhere? Did you ever get a chance to setup virtuabox? Might be tough with your low memory :\

**Comment by ykris45** [comment]
@tzarebczan i doesnt have Virtual Machine .. so its based on your DM earlier

**Pull request closed without merging**
