### PR TITLE
Add Screenshot To the Tipbot FAQs

### PR DESCRIPTION
**Pull request by ykris45**

### CODE REVIEW

**Comment by tzarebczan** [comment]
@ykris45 don't need a screenshot for each discord command - just the !tip help one please. Please run this locally to make sure it looks correct with new lines also.

For twitter, please remove the screenshot and add something like this which will display the tweet: https://github.com/lbryio/lbry.io/blob/555982aede433e6c042369416172608543a5bde0/content/news/03-5-questions-about-lbry.md

Reddit looks good, but maybe find another shorter example to screenshot?

**Comment by tzarebczan** [comment]
@ykris45 please remove the twitter screenshot for now or try to replace it with the actual tweet as I mentioned.

**Comment by ykris45** [comment]
@tzarebczan please collaborate with me. m.justi embed your tweet https://twitter.com/TomZarebczan/status/991901394218176512

**Comment by ykris45** [comment]
screenshot_2018-05-24-02-44-23-128
screenshot_2018-05-24-02-45-41-281

**Pull request merged**
