### PR TITLE
add footer to homepage

### PR DESCRIPTION
**Pull request by ykris45**
based on @Invariant-Change commented on my earlier pull request about add telegram icons on footer

### Preview 
screenshot_2018-06-10-16-05-53-349

### CODE REVIEW

**Comment by Invariant-Change** [comment]
See: https://github.com/lbryio/lbry.io/pull/588

**Comment by tzarebczan** [comment]
@kauffj okay with adding the footer to the main page?

**Comment by kauffj** [comment]
I don't think we need a footer on a page that doesn't scroll. @netoperatorwibby is welcome to change this as part of his redesign work.

**Comment by ykris45** [comment]
@kauffj im sure the footer is most important things for a website. most website in the world using footer. and displayed to every part of website also. for example homepage. and people will see about TOS. Privacy Policy and also every part who doesnt include on header. i think lbry hiring page also. hehe.

**Pull request closed without merging**
