### PR TITLE
add twitter id and github id team

### PR DESCRIPTION
**Pull request by ykris45**
add twitter and github id

### CODE REVIEW

**Comment by ykris45** [comment]
i think its so clear  but i cannot find igassmann and blckchnprncss twitter page. @tzarebczan

**Comment by ykris45** [comment]
Finished...the other team i didnt they social media account

**Comment by tzarebczan** [comment]
Thanks for doing this @ykris45 - Fixed Josh's twitter and added Natalie's Twitter.

**Comment by ykris45** [comment]
you welcome sir. thanks for collaboration again with mine.hehe

**Pull request merged**
