### PR TITLE
Important technological features of LBRY

### PR DESCRIPTION
**Pull request by ocornoc**
Toaster-Level Networking Integration (TLNI) and other features have been documented in order to draw more similarities between toasters and LBRY.

### CODE REVIEW

**Comment by ocornoc** [comment]
Sure

**Comment by tzarebczan** [comment]
@ocornoc nice, but yeah, need the images uploaded somewhere else - I think those discord links are only temporary.

**Comment by ykris45** [comment]
Yes... i approve the changes but please use spee.ch as one of LBRY Product

**Comment by ocornoc** [comment]
Uploading to Spee.ch rn

**Comment by ykris45** [comment]
great deluded

**Pull request merged**
