### PR TITLE
Formatted Page With Extras

### PR DESCRIPTION
**Pull request by Invariant-Change**
Just gave the page a cleanup added "**OPEN IN LBRY**" buttons (with open links) and made the markup compatible with **accessibility devices**.

Although _multiple_ **H1 tags** can be used, they are **not** _best practice_ due to accessibility **issues**.
image

### CODE REVIEW

**Comment by tzarebczan** [comment]
@jamesbiller can you run this locally to see if it's something you'd like merged.

**Comment by jamesbiller** [comment]
You got it chief!

**Comment by Invariant-Change** [comment]
Currently working blind as I don't have lbry.io set up on a local server, but all should hopefully look like I imagined :)

**Comment by Invariant-Change** [comment]
Oh and forgot to say... Images sizes should always be in HTML. This will help speed up page load times and make a page compatible with every device/browser.

**Comment by Invariant-Change** [comment]
Still learning Git, so looking to see what happened.

**Pull request closed without merging**
