### PR TITLE
Update fontawesome to latest version of 4

### PR DESCRIPTION
**Pull request by maximest-pierre**
Update font awesome to latest of release of version 4

### CODE REVIEW

**Comment by ykris45** [comment]
@maximest-pierre thanks bro. LGTM

**Comment by jsigwart** [comment]
Why update to version 4? Version 5 is out.

**Comment by maximest-pierre** [comment]
Its a drop in replacement instead of redoing a some of the code. There is also not that much to gain from upgrading to 5 right now. I would wait for a complete redesign before upgrading to version 5.

**Comment by ykris45** [comment]
@maximest-pierre if my PR and your PR in this comment merged. it shouldnt break lbry.io page guys ?.

**Comment by tzarebczan** [comment]
I'll review this by the end of the week.

**Comment by ykris45** [comment]
@tzarebczan I hope if this PR merge . doesnt affect or broke my PR. because i import Font awesome to the layout/basic.php

**Pull request merged**
