### PR TITLE
add bio html to show social links author

### PR DESCRIPTION
**Pull request by ykris45**
is there anyone who wants to test this on local. I am sure it can display twitter, github and email id Author. I try on my local machine but error out of memory

### CODE REVIEW

**Comment by maximest-pierre** [comment]
This is the result:

screenshot from 2018-03-01 13-23-33

To get the social link and github id a modification on post.class.php is needed and also ContentActions.class.php.  

Example: 
# post.class.php

Add the following code
``` 
public function getAuthorGithubID()
{
   $post = ContentActions::prepareBioPartial(['person' =>$this->author]);

    return $post["github"];
}

public function getAuthorTwitterID()
{
    $post = ContentActions::prepareBioPartial(['person' =>$this->author]);

    return $post["twitter"];
}

public function getAuthorEmail()
{
    $post = ContentActions::prepareBioPartial(['person' =>$this->author]);

    return $post["email"];
}
 ```
# ContentActions.class.php

Modify this code from: 
```
public static function preparePostAuthorPartial(array $vars): array
  {
    $post = $vars['post'];
    return [
      'authorName'    => $post->getAuthorName(),
      'photoImgSrc'   => $post->getAuthorPhoto(),
      'authorBioHtml' => $post->getAuthorBioHtml()
    ];
  }
```
to this:
```
public static function preparePostAuthorPartial(array $vars): array
  {
    $post = $vars['post'];
    return [
      'authorName'    => $post->getAuthorName(),
      'photoImgSrc'   => $post->getAuthorPhoto(),
      'authorBioHtml' => $post->getAuthorBioHtml(),
      'authorGithub' => $post->getAuthorGithubID(),
      'authorTwitter' => $post->getAuthorTwitterID(),
      'authorEmail' => $post->getAuthorEmail()
    ];
  }
```
Then you can acces the github id with $authorGithub inside of _postAuthor.php

PS. they may be some errors with what I wrote

**Comment by ykris45** [comment]
@maximest-pierre review this please?

**Comment by maximest-pierre** [comment]
I fix some minor problems. I am going to let someone else look at it to make sure everything is good.

**Comment by ykris45** [comment]
@maximest-pierre thanks for colaboration with me. thats is my ideas to make lbry.io better

**Comment by ykris45** [comment]
@tzarebczan what do you think sir about this product?

**Comment by tzarebczan** [comment]
I'll give it a shot locally today.

**Comment by ykris45** [comment]
okay. bacause i try it into my local machine but out of memory

**Comment by tzarebczan** [comment]
@maximest-pierre / @ykris45 it needs to handle cases where Twitter/Github data doesn't exist.  Example: http://localhost:8000/news/stop-net-banality

Also, can we move the icons closer to the name, and then leave the space between icons/bio?

**Comment by ykris45** [comment]
@tzarebczan screenshot please . out of memory

**Comment by tzarebczan** [comment]
eeeeeeee

**Comment by maximest-pierre** [comment]
screenshot from 2018-03-02 15-51-02

**Comment by ykris45** [comment]
@maximest-pierre did you know if i accesed localhost:8000/news it says this Fatal error: Maximum execution time of 60 seconds exceeded in C:\Users\CHRIS\Documents\GitHub\lbry.io\model\Post.class.php on line 32

**Comment by ykris45** [comment]
samuel bryan didnt have email

**Comment by maximest-pierre** [comment]
Can't seem to replicate the problem that you have but line 32 is the one where the site loads all the markdown and there is like 160 something file to load.

**Comment by ykris45** [comment]
@kauffj maybe today i will test it via android mobile.. because using computer it says out of memory

**Comment by kauffj** [comment]
@ykris45 both out of memory and execution time exceeded errors are likely due to infinite loops

**Comment by ykris45** [comment]
screenshot_2018-03-10-05-07-55-724
@kauffj tested locally with my android..

**Comment by ykris45** [comment]
screenshot_2018-03-10-05-55-53-013
Done @tzarebczan and @kauffj .  thanks God

**Pull request merged**
