### PR TITLE
add telegram icon and link to footer

### PR DESCRIPTION
**Pull request by ykris45**
based @jsigwart ideas on #bounty channel LBRY Discord Server. 
## My Preview Screenshot
screenshot_2018-06-03-06-08-23-010

### CODE REVIEW

**Comment by jsigwart** [comment]
This has to be done differently. The footer is a partial html page that is pulled in, so adding a head tag is not appropriate here. You need to modify the head tag in the correct header file.

**Comment by maximest-pierre** [comment]
You don't need to import font-awesome its suppose to already imported in the CSS

**Comment by ykris45** [comment]
but in css file there no icon telegram

**Comment by maximest-pierre** [comment]
It could be an old version of font-awesome let me look it up

**Comment by maximest-pierre** [comment]
our version of font-awesome doesn't have the telegram icon

**Comment by maximest-pierre** [comment]
I open an issue for an update to font-awesome #589

**Comment by tzarebczan** [comment]
shouldn't this go after Discord?

**Comment by ykris45** [comment]
@jsigwart here the result . i found the correct header file on layout/basic.php
image

**Comment by ykris45** [comment]
@jsigwart its ready to merge. based on your reverting font awesome to earlier version

**Comment by Invariant-Change** [comment]
*Should be a top menu item [JOBS]. No one is going to see it hidden in the footer.

**Comment by Invariant-Change** [comment]
No footer on the homepage 😮 = No "LBRY is hiring!" link!

image

**Pull request merged**
