### PR TITLE
Move social share to the top off article

### PR DESCRIPTION
**Pull request by ykris45**
screenshot_2018-05-25-03-30-27-846
for looks more obsivius

### CODE REVIEW

**Comment by tzarebczan** [comment]
LGTM, @jsigwart / @maximest-pierre please review.

**Comment by jsigwart** [comment]
I am good with this, although when we do the website redesign, we should figure how to make it clear the social icons are for sharing the article, and not LBRY's generic social media accounts. I had no idea until a few weeks ago that we had sharing links for articles.

**Comment by maximest-pierre** [comment]
Sorry, I just saw this PR. This LGTM. :+1:

**Comment by tzarebczan** [comment]
@jsigwart / @ykris45 how can we make this clearer? Maybe just text that says: "Share: " in front of the icons?

**Comment by ykris45** [comment]
screenshot_2018-05-29-21-35-41-857
add badge near the icon to know what the purpose of social icons
@tzarebczan

**Comment by tzarebczan** [comment]
@maximest-pierre , Chris can't figure out how to align that bade properly with the share icons. Can you give this a shot? If it's troublesome,  then maybe just a label in front of the share icons.

**Comment by kauffj** [comment]
A badge is not an appropriate style for this. I would play around with various headers with the class `meta` (e.g. `<h5 class="meta">). Also, the label needs to appear directly over the icons.

**Comment by maximest-pierre** [comment]
screenshot from 2018-05-29 23-11-00

I managed to do this using 

```<h4 class="social-share-title">Share this article</h4>``` in the ```_postSocialShare.php```

and adding an entry in _content.scss  at line 27 

```.social-share-title
{
  text-align: center
}
```

This is one of many solutions to this

**Comment by kauffj** [comment]
I still have some design objections to this. It may be time to start bringing @netoperatorwibby into this project as well...

**Comment by tzarebczan** [comment]
Putting this on-hold until @NetOperatorWibby has a moment to take a look.

**Comment by NetOperatorWibby** [comment]
This issue will be addressed in the forthcoming redesign. Closing for now.

**Pull request closed without merging**
