### PR TITLE
Delete quickstart and other instances

### PR DESCRIPTION
**Pull request by ykris45**
### Description

Delete quickstart and other files related to quickstart pages

### CODE REVIEW

**Comment by ykris45** [comment]
@tzarebczan Tested locally and its works fine. #880

**Comment by tzarebczan** [comment]
@ykris45 I think there are some more places where quickstart related items can be removed. Want to take another look?

**Comment by ykris45** [comment]
@tzarebczan yes i want to take another look.  please guide me where quickstar related items can be removed by input reference on this.

**Comment by ykris45** [comment]
@tzarebczan these files is related to quickstart and im done to take this chance, please review and test on your machine, i already test and like i said it will redirect to lbry.tech/playground

**Comment by ykris45** [comment]
@tzarebczan done and done

**Pull request merged**
