### PR TITLE
lbry-android.md

### PR DESCRIPTION
**Pull request by ceoger**
LBRY-Android-App-Faq

### CODE REVIEW

**Comment by ykris45** [comment]
@clement please close it. You have Correct PR it will make https://lbry.io/faq/lbry-basics broken.

**Comment by tzarebczan** [comment]
@Invariant-Change to take a stab at helping out as well.

**Comment by ceoger** [comment]
@Invariant-Change please ignore the others i tagged you and look into this, thanks

**Comment by tzarebczan** [comment]
@Invariant-Change can you give this a once through before I review/add onto?

**Comment by Invariant-Change** [comment]
Is this a markup error or meant to be there?
image

**Comment by ceoger** [comment]
meant to be there, an anchor link that goes directly into that section sections link `lbry.io/faq/android-basics#downloads`

**Comment by Invariant-Change** [comment]
Ahh, it's not working in GitHub [preview](https://github.com/lbryio/lbry.io/blob/1198e4f1e01c43720741aa425d867c6524718988/content/faq/lbry-android.md). But I know GitHub has issues with MarkDown.

**Comment by Invariant-Change** [comment]
Can you just check the code outputs correctly. The anchor markdown I use is this:
image

**Comment by tzarebczan** [comment]
Yup, those should work on the live site. I'll give this a final review tomorrow.

**Comment by Invariant-Change** [comment]
There might be a few sneaky corrections still. But all the main ones are fixed with the above code.

**Comment by tzarebczan** [comment]
Going to close and merge this directly because it's trying to delete lbry-basics.md.

**Comment by tzarebczan** [comment]
Thanks for this Clement, it's live!

**Pull request closed without merging**
