### PR TITLE
2018/2019 post

### PR DESCRIPTION
**Pull request by kauffj**
### Fixes #

### CODE REVIEW

**Comment by kauffj** [comment]
@robvsmith merge whenever you want this to go live

**Comment by tzarebczan** [comment]
@kauffj / @robvsmith Who clean up (i.e some say "help wanted") some of the internal issues the roadmap (https://lbry.io/roadmap) is pulling from https://github.com/lbryio/internal-issues/issues?q=is%3Aopen+is%3Aissue+label%3A2019?

**Comment by kauffj** [comment]
I will

**Comment by kauffj** [comment]
(I did)

**Pull request merged**
