### PR TITLE
Modify Press-Kit page

### PR DESCRIPTION
**Pull request by ykris45**
# BEFORE
image
# AFTER
image

For make this page looks Pretty

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

### CODE REVIEW

**Comment by kauffj** [comment]
You're learning @ykris45! But better to just render the template than copy and paste the code. This is a best practice in programming known as [Don't Repeat Yourself](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

However, before you do even that, @Feanor78 do you want to keep this page? It's pretty out of date. Probably better it not exist unless it's going to be current.

**Comment by ykris45** [comment]
Yessir.. i will learning more better than before.. Thanks for always support me to learn about programming sir.

**Comment by ykris45** [comment]
@Feanor78 please review it brinck

**Comment by ykris45** [comment]
@alyssaoc why its On Hold?

**Comment by alyssaoc** [comment]
@ykris45 we were waiting on the press kit modifications, but I will find out more

**Pull request closed without merging**
